spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_NAME}
    password: ${PROD_DB_PASSWORD}
    name: portal-simdetails

  sql:
    init:
      mode: always # we won't do this in prod, I am just doing this for demo purposes


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/simdetails
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
